### ISSUE TITLE
WPF: EmployeeView - CheckBox IsDeveloper is not binded with model

### ISSUE THREAD

**Issue by tkovnik** [thomasclaudiushuber/mvvmgen-samples#1]
Project: EmployeeManager.Wpf
EmployeeView.Xaml line 38.

CheckBox does not have its property IsChecked binded with model property "IsDeveloper". Changes on UI does not commit into model.

----
Great library btw! Was looking for some alternative to MVVMLight.

**Comment by thomasclaudiushuber** [comment]
Thanks @tkovnik, great catch! 👍🏼

It's fixed now. 

--- 

Happy to read you like the library.
