### ISSUE TITLE
RegistrationScreen.Wpf fails to build

### ISSUE THREAD

**Issue by r14958** [thomasclaudiushuber/mvvmgen-samples#3]
When building or rebuilding the solution RegistrationScreen the following errors appear in the Output Window:
1>D:\Users\...\mvvmgen-samples\RegistrationScreen\RegistrationScreen.Wpf\ViewModel\MainViewModel.cs(31,35,31,44): error CS0103: The name 'FirstName' does not exist in the current context
1>Done building project "RegistrationScreen.Wpf_mtlcf25z_wpftmp.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I briefly see this error appear in my Error List window, but then it disappears on its own.  The project still fails to run/debug or build.
Could the compiler be "catching" this error during the build before the source generators can finish generating the code?

**Comment by hari-work** [comment]
faced the similar issue on my .net core 3.1 project as well. Design time it works fine, compile time it appears the generated files are not not found!

**Comment by thomasclaudiushuber** [comment]
Hey @r14958 @hari-work Did you have the issue with the samples here or with your own projects? 

WPF had a problem with Source Generators (as it does a 2-step-compilation with all the XAML code) that should be resolved with the latest .NET 5 SDK and also with the .NET 6 SDK.

**Comment by thomasclaudiushuber** [comment]
OK, I updated all projects to the latest version of MvvmGen and also to .NET 6. Everything works. Please open this issue again if you still have problems.
